/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as BlogIdRouteImport } from './routes/blog.$id'
import { Route as AdminSiteContentRouteImport } from './routes/admin/site-content'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminOffersRouteImport } from './routes/admin/offers'
import { Route as AdminNewsletterRouteImport } from './routes/admin/newsletter'
import { Route as AdminHeroRouteImport } from './routes/admin/hero'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminContactsRouteImport } from './routes/admin/contacts'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminBlogsRouteImport } from './routes/admin/blogs'
import { Route as AdminBannersRouteImport } from './routes/admin/banners'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BlogRoute,
} as any)
const AdminSiteContentRoute = AdminSiteContentRouteImport.update({
  id: '/site-content',
  path: '/site-content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOffersRoute = AdminOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeroRoute = AdminHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsRoute = AdminBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/wishlist': typeof WishlistRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-content': typeof AdminSiteContentRoute
  '/blog/$id': typeof BlogIdRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/wishlist': typeof WishlistRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-content': typeof AdminSiteContentRoute
  '/blog/$id': typeof BlogIdRoute
  '/product/$id': typeof ProductIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/wishlist': typeof WishlistRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-content': typeof AdminSiteContentRoute
  '/blog/$id': typeof BlogIdRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faqs'
    | '/login'
    | '/offers'
    | '/reset-password'
    | '/shop'
    | '/signup'
    | '/wishlist'
    | '/admin/banners'
    | '/admin/blogs'
    | '/admin/categories'
    | '/admin/contacts'
    | '/admin/customers'
    | '/admin/hero'
    | '/admin/newsletter'
    | '/admin/offers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/site-content'
    | '/blog/$id'
    | '/product/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faqs'
    | '/login'
    | '/offers'
    | '/reset-password'
    | '/shop'
    | '/signup'
    | '/wishlist'
    | '/admin/banners'
    | '/admin/blogs'
    | '/admin/categories'
    | '/admin/contacts'
    | '/admin/customers'
    | '/admin/hero'
    | '/admin/newsletter'
    | '/admin/offers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/site-content'
    | '/blog/$id'
    | '/product/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faqs'
    | '/login'
    | '/offers'
    | '/reset-password'
    | '/shop'
    | '/signup'
    | '/wishlist'
    | '/admin/banners'
    | '/admin/blogs'
    | '/admin/categories'
    | '/admin/contacts'
    | '/admin/customers'
    | '/admin/hero'
    | '/admin/newsletter'
    | '/admin/offers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/site-content'
    | '/blog/$id'
    | '/product/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  LoginRoute: typeof LoginRoute
  OffersRoute: typeof OffersRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShopRoute: typeof ShopRoute
  SignupRoute: typeof SignupRoute
  WishlistRoute: typeof WishlistRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/site-content': {
      id: '/admin/site-content'
      path: '/site-content'
      fullPath: '/admin/site-content'
      preLoaderRoute: typeof AdminSiteContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/offers': {
      id: '/admin/offers'
      path: '/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AdminOffersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hero': {
      id: '/admin/hero'
      path: '/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AdminHeroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs': {
      id: '/admin/blogs'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminBlogsRoute: typeof AdminBlogsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminHeroRoute: typeof AdminHeroRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminOffersRoute: typeof AdminOffersRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSiteContentRoute: typeof AdminSiteContentRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminBlogsRoute: AdminBlogsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminHeroRoute: AdminHeroRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminOffersRoute: AdminOffersRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSiteContentRoute: AdminSiteContentRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogIdRoute: typeof BlogIdRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogIdRoute: BlogIdRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  LoginRoute: LoginRoute,
  OffersRoute: OffersRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShopRoute: ShopRoute,
  SignupRoute: SignupRoute,
  WishlistRoute: WishlistRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
